language: cpp
compiler: clang
before_install: 
 - sudo apt-get update
 - sudo apt-get dist-upgrade -y
 - clang --version
install: clang make automake libsdl1.2-dev libogg-dev libsdl-image1.2-dev libcurl4-openssl-dev libopenal-dev libvorbis-dev 
script: cd source/src && make